export const ActionTypes = {
    SET_PROFILES : "SET_PROFILES",
    SELECTED_PROFILES :  "SELECTED_PROFILES",
    REMOVE_SELECTED_PROFILES: "REMOVE_SELECTED_PROFILES",
    FILTER_PROFILE_BY_NAME : "FILTER_PROFILE_BY_NAME"
};